export * from "./county/CountyPackService.js";
export * from "./county/CountyQuestionService.js";
export * from "./county/schema.js";
export * from "./county/types.js";
export {
  CALIFORNIA_COUNTY_INDEX,
  CALIFORNIA_DISTRICT_CANDIDATE_PACK,
  CENSUS_2024_COUNTY_GAZETTEER_SOURCE,
  DistrictCandidatePackValidationError,
  DistrictCuratedPackValidationError,
  DistrictPlaceAnchorPackValidationError,
  FIRST_CALIFORNIA_SECOND_DISTRICT_CANDIDATE,
  US_COUNTY_INDEX,
  US_COUNTY_INDEX_SOURCE_URL,
  US_COUNTY_INDEX_SOURCE_YEAR,
  US_STATE_LABEL_BY_CODE,
  californiaCountyIndexSourceNotes,
  createNationalWorldService,
  createDistrictReadinessAggregate,
  createDistrictOwnerGateCutline,
  createDistrictPromotionPacket,
  DISTRICT_PROMOTION_GATE_ORDER,
  NationalWorldService,
  normalizeWorldPlaceCategory,
  parseDistrictCandidatePack,
  parseDistrictCuratedPack,
  parseDistrictPlaceAnchorPack,
  usCountyIndexSourceNotes,
  publicCoverageBoundaryDto,
  hiddenDraftEvidenceBoundaryDto,
  futureHostedClawdBoundaryDto,
  NATIONAL_GENERATION_PRODUCTION_STAGES,
  evaluateNationalGenerationProductionReadiness,
  PUBLIC_PLAYABLE_TOOLS,
  SCENE_PACKET_CACHE_CONTRACT_UPDATE_ID,
  assertScenePacketCachePlanSafe,
  createScenePacketCacheKey,
  createScenePacketCachePlan,
  hashScenePacketViewportFrame,
  scenePacketCachePolicyForReadiness,
} from "./world/index.js";
export type {
  AtlasProductBackendDtoKind,
  CaliforniaDistrictCandidateArchetype,
  CaliforniaDistrictCandidatePackEntry,
  CaliforniaDistrictSceneStressor,
  CountyCoverageDistrictIndexEntry,
  CountyCoverageTierCount,
  CountyCoverageTier,
  DistrictCandidateAnchorRequirement,
  DistrictCandidatePack,
  DistrictCandidateSceneStressor,
  DistrictCandidateSourceNote,
  DistrictCuratedAnchor,
  DistrictCuratedPack,
  DistrictOwnerGateCutline,
  DistrictOwnerGateCutlineInput,
  DistrictOwnerGateCutlineOutcome,
  DistrictOwnerGateDecision,
  DistrictOwnerGateId,
  DistrictOwnerGateStatus,
  FutureHostedClawdBoundaryDto,
  HiddenDraftEvidenceBoundaryDto,
  DistrictPlaceAnchor,
  DistrictPlaceAnchorPack,
  DistrictPlaceAnchorRole,
  DistrictProductProofState,
  DistrictPromotionCountyState,
  DistrictPromotionDraftSceneSummary,
  DistrictPromotionFilePresence,
  DistrictPromotionPacket,
  DistrictPromotionPacketInput,
  DistrictReadinessAggregate,
  DistrictReadinessAggregatorInput,
  DistrictReadinessBlockerGroups,
  DistrictReadinessEvidenceState,
  DistrictSourceToSceneTrace,
  DistrictSourceVerifierState,
  DistrictSplitGuardState,
  DistrictVisualPacketState,
  NationalCountyIndexEntry,
  ProviderLookupReadiness,
  UsCoverageDirectoryResponse,
  UsCountryResponse,
  UsCountySummary,
  UsCountyWorldResponse,
  UsDistrictSummary,
  UsDistrictWorldResponse,
  UsPlaceSummary,
  UsStateCountiesResponse,
  UsStateSummary,
  UsUnsupportedWorldResponse,
  UsWorldIdentity,
  UsWorldScope,
  PublicCoverageBoundaryDto,
  PublicPlayableToolKey,
  NationalGenerationProductionInput,
  NationalGenerationProductionReadiness,
  NationalGenerationProductionStage,
  NationalGenerationProductionStageId,
  WorldLookupPlaceInput,
  WorldLookupPlaceSummary,
  WorldLookupResolvedLocation,
  WorldCachePolicy,
  WorldPlaceCategory,
  WorldPlaceLookupResponse,
  WorldSourceKind,
  WorldSourceNote,
  ScenePacketCacheKey,
  ScenePacketCacheKeyInput,
  ScenePacketCacheKeyParts,
  ScenePacketCachePlan,
  ScenePacketCachePlanInput,
  ScenePacketCachePolicy,
  ScenePacketCacheSafetyResult,
  ScenePacketCacheStorageMode,
  ScenePacketGenerationJob,
  ScenePacketGenerationJobStatus,
  ScenePacketGenerationMode,
  ScenePacketPayloadBoundary,
  ScenePacketReadiness,
  ScenePacketViewportFrame,
} from "./world/index.js";
export {
  CampaignPreviewService,
  ScoutDropService,
  previewCampaignFromScout,
  previewScoutDrop,
} from "./scout/index.js";
export {
  CITY_WORLD_TILE_BASIS,
  compileCityWorldScene,
  compileCountyShellCityWorldScene,
  compileDistrictPlaceAnchorDraftCityWorldScene,
  DETERMINISTIC_GENERATED_DISTRICT_UPDATE_ID,
  generateParametricCityWorldScene,
  exampleParametricDistrictSpec,
  createDeterministicGeneratedDistrictScene,
  createDeterministicGeneratedDistrictSpec,
  deterministicGeneratedDistrictSeedForCounty,
  resolveCountyParameters,
  GENERATED_MASSING_SIGNATURE_DISTANCE_FLOOR,
  analyzeGeneratedDistrictMassingSignature,
  analyzeGeneratedDistrictParity,
  analyzeGeneratedLandmark,
  analyzeCityWorldScene,
  analyzeCityWorldObjectKit,
  assignCityWorldObjectKit,
  CITY_WORLD_BUILDING_PALETTES,
  GENERATED_LANDMARK_SIGNATURES,
  GENERATED_DISTRICT_ARCHETYPES,
  ARCHETYPE_PROFILES,
  NAME_SIGNAL_TOKENS,
  REGIONAL_BUILDING_PALETTES,
  REGIONAL_PALETTES,
  REGION_PROFILES,
  STATE_TO_DIVISION,
  resolveEffectiveBuildingColors,
  expectedGeneratedLandmarkKind,
  generatedLandmarkSilhouetteKey,
  generatedDistrictMassingSignatureDistance,
  regionalBuildingPaletteKey,
  regionalTerrainPaletteKey,
  resolveRegionalBuildingPalette,
  cityWorldBuildingTouchesLot,
  cityWorldDiamondPoints,
  cityWorldExpandViewportFrame,
  cityWorldFrameContainsFrame,
  cityWorldLotTouchesRoad,
  cityWorldScreenCenterForCamera,
  cityWorldViewportFrameForScreenCamera,
  cityWorldViewportFrameForPreset,
  compileVoxelSceneFromCountyPack,
  createVoxelNote,
  createVoxelSticker,
  CITY_WORLD_MOBILE_LOD_BUDGETS,
  CITY_WORLD_RENDER_LAYER_BUDGETS,
  CITY_WORLD_RENDER_LAYER_ORDER,
  CITY_WORLD_SCENE_WINDOW_BUDGETS,
  CITY_WORLD_SCENE_WINDOW_DEFAULT_CHUNK_SIZE,
  buildCityWorldRenderCommandBuffer,
  buildCityWorldSceneItemIndex,
  cityWorldBuildingDepthKey,
  cityWorldPropDepthKey,
  compareCityWorldDepthInterleaveItems,
  compileCityWorldSceneChunkIndex,
  compileCityWorldSceneWindow,
  createCityWorldSceneWindowCompiler,
  deriveCityWorldMobileOcclusion,
  deriveCityWorldTerrainMap,
  evaluateCityWorldMobileLodBudget,
  evaluateCityWorldRenderLayerBudget,
  evaluateCityWorldSceneWindowBudget,
  projectCityWorldPoint,
  sampleCityWorldViewportForCameraPreset,
  serializeVoxelMapSession,
  unprojectCityWorldGroundPoint,
  validateVoxelWorld,
  withBuildingMetadata,
  withCityWorldTerrainContactMetadata,
  withLotMetadata,
  withPropMetadata,
  withRoadMetadata,
} from "./voxel/index.js";
export type {
  CreateVoxelNoteInput,
  CreateVoxelStickerInput,
  VoxelMapSession,
} from "./voxel/mapSession.js";
export type { CountyShellCityWorldInput, DistrictPlaceAnchorDraftCityWorldInput } from "./voxel/cityWorldCompiler.js";
export type {
  CityWorldParametricSpec,
  CityWorldParametricResult,
  CityWorldZoneSpec,
  CityWorldZoneKind,
  CityWorldRoadSeed,
  CityWorldGeneratedDistrictParityReport,
  CityWorldGeneratedMassingSignature,
  CityWorldGeneratedFrameBandDensity,
  CityWorldGeneratedLandmarkHostCell,
  CityWorldGeneratedLandmarkKind,
  CityWorldGeneratedLandmarkReadout,
  CityWorldGeneratedLandmarkSignature,
  CityWorldGeneratedPadMetric,
} from "./voxel/cityWorldParametricGenerator.js";
export type {
  AridityBand,
  ArchetypeProfile,
  CensusDivision,
  CountyGenerationClimate,
  CountyGenerationEnvelope,
  CountyGenerationModulation,
  CountyGenerationParameters,
  LatitudeBand,
  NameSignal,
  RegionProfile,
} from "./voxel/cityWorldCountyParameters.js";
export type {
  DeterministicGeneratedDistrictInput,
  DeterministicGeneratedDistrictSceneResult,
  DeterministicGeneratedDistrictSpec,
  GeneratedDistrictArchetype,
} from "./voxel/cityWorldGeneratedDistrict.js";
export type { RegionalPalette } from "./voxel/cityWorldRegionalPalettes.js";
export type {
  CampaignAssetPlaceholder,
  CampaignChannel,
  CampaignDayPlan,
  CampaignPreviewState,
  CampaignRoutePriority,
  AlphaPreviewBoundary,
  ScoutDropInput,
  ScoutPreviewState,
  ScoutRisk,
  ScoutRouteStop,
  ScoutSignal,
} from "./scout/index.js";
export { riversideDemoVoxelScene } from "./voxel/riversideDemoScene.js";
export type {
  AtlasEdge,
  AtlasEdgeKind,
  AtlasMarker,
  AtlasMarkerKind,
  AtlasNode,
  AtlasNodeKind,
  CampaignPreviewPanel,
  CampaignAssetPanelItem,
  CampaignDayPanelItem,
  CampaignRoutePriorityPanelItem,
  ClawdRenderState,
  ScoutReportPanel,
  UpgradePanel,
  VoxelAmbientState,
  VoxelDistrict,
  VoxelFlowStep,
  VoxelNote,
  VoxelPlace,
  VoxelPlaceKind,
  VoxelPoint as VoxelScenePoint,
  VoxelScene,
  VoxelSticker,
  VoxelStickerKind,
  VoxelTheme,
  VoxelTile,
  VoxelTileKind,
  VoxelWorld,
  VoxelWorldNode,
  VoxelWorldScale,
} from "./voxel/types.js";
export type {
  CityWorldActor,
  CityWorldAtlasMetadata,
  CityWorldAmbient,
  CityWorldBounds,
  CityWorldBuilding,
  CityWorldObjectKitMetadata,
  CityWorldObjectKitPaletteRole,
  CityWorldObjectKitPrefabFamily,
  CityWorldCameraPreset,
  CityWorldDetailLevel,
  CityWorldFacadeStyle,
  CityWorldHudDefaults,
  CityWorldLot,
  CityWorldPin,
  CityWorldPlace,
  CityWorldPoint,
  CityWorldProp,
  CityWorldRegion,
  CityWorldRoofShape,
  CityWorldRoadSegment,
  CityWorldScene,
  CityWorldSessionState,
  CityWorldTerrainTile,
} from "./voxel/cityWorldTypes.js";
export type {
  CityWorldProjectedPoint,
  CityWorldScreenCameraState,
  CityWorldViewportFrame,
} from "./voxel/cityWorldBasis.js";
export type {
  CityWorldCivicVenueStressCellKind,
  CityWorldCivicVenueStressCellMetric,
  CityWorldEngineDiagnosticAxis,
  CityWorldEngineDiagnosticIssue,
  CityWorldEngineDiagnosticReport,
  CityWorldEngineDiagnosticScenario,
} from "./voxel/cityWorldDiagnostics.js";
export type {
  CityWorldObjectKitFamilyMetric,
  CityWorldObjectKitReport,
} from "./voxel/cityWorldObjectKit.js";
export type {
  CityWorldDerivedTerrainCell,
  CityWorldDerivedTerrainMap,
  CityWorldMobileLodBudget,
  CityWorldMobileLodBudgetProfileId,
  CityWorldMobileLodBudgetResult,
  CityWorldMobileOcclusionReport,
} from "./voxel/cityWorldDerivedTerrainMap.js";
export type {
  CityWorldDepthInterleaveItem,
  CityWorldDepthInterleaveKind,
  CityWorldRenderBudgetProfileId,
  CityWorldRenderCommand,
  CityWorldRenderCommandBuffer,
  CityWorldRenderCommandBufferOptions,
  CityWorldRenderCommandKind,
  CityWorldRenderLayerBudget,
  CityWorldRenderLayerBudgetResult,
  CityWorldRenderLayerId,
  CityWorldRenderLayerSummary,
} from "./voxel/cityWorldRenderCommands.js";
export type {
  CityWorldSceneChunk,
  CityWorldSceneChunkIndex,
  CityWorldSceneItemIndex,
  CityWorldSceneWindow,
  CityWorldSceneWindowBudget,
  CityWorldSceneWindowBudgetProfileId,
  CityWorldSceneWindowBudgetResult,
  CityWorldSceneWindowOptions,
} from "./voxel/cityWorldSceneWindow.js";
export type {
  CityWorldAtlasAnchor,
  CityWorldAtlasFallbackKind,
  CityWorldAtlasFrame,
  CityWorldAtlasKind,
  CityWorldAtlasManifest,
  CityWorldAtlasPalette,
  CityWorldAtlasSprite,
  CityWorldAtlasTile,
  CityWorldAtlasValidationResult,
} from "./voxel/cityWorldAtlas.js";
export {
  REQUIRED_CITY_WORLD_ATLAS_TAGS,
  validateCityWorldAtlasManifest,
  validateCityWorldSceneAtlasKeys,
} from "./voxel/cityWorldAtlas.js";

export type AtlasPhase = "skeleton" | "county-pack" | "renderer" | "scout-drop" | "campaign" | "mcp-tools";

export type AtlasPackageStatus = {
  packageName: string;
  phase: AtlasPhase;
  readyForProductLogic: boolean;
};

export const CORE_PACKAGE_STATUS: AtlasPackageStatus = {
  packageName: "@atlas/core",
  phase: "campaign",
  readyForProductLogic: true,
};
