import type { NationalCountyIndexEntry, WorldSourceNote } from "./types.js";

export const CENSUS_2024_COUNTY_GAZETTEER_SOURCE: WorldSourceNote = {
  source: "census",
  label: "2024 Census county gazetteer",
  attribution: "U.S. Census Bureau Gazetteer Files, 2024 county national file",
  ttlSeconds: 60 * 60 * 24 * 365,
};

export const CALIFORNIA_COUNTY_INDEX: NationalCountyIndexEntry[] = [
  {
    geoid: "06001",
    stateCode: "CA",
    name: "Alameda County",
    countySlug: "alameda-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 37.647139, longitude: -121.912488 },
  },
  {
    geoid: "06003",
    stateCode: "CA",
    name: "Alpine County",
    countySlug: "alpine-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 38.621783, longitude: -119.798352 },
  },
  {
    geoid: "06005",
    stateCode: "CA",
    name: "Amador County",
    countySlug: "amador-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 38.443549, longitude: -120.653858 },
  },
  {
    geoid: "06007",
    stateCode: "CA",
    name: "Butte County",
    countySlug: "butte-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 39.665336, longitude: -121.603209 },
  },
  {
    geoid: "06009",
    stateCode: "CA",
    name: "Calaveras County",
    countySlug: "calaveras-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 38.191068, longitude: -120.554107 },
  },
  {
    geoid: "06011",
    stateCode: "CA",
    name: "Colusa County",
    countySlug: "colusa-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 39.177739, longitude: -122.237563 },
  },
  {
    geoid: "06013",
    stateCode: "CA",
    name: "Contra Costa County",
    countySlug: "contra-costa-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 37.919479, longitude: -121.951543 },
  },
  {
    geoid: "06015",
    stateCode: "CA",
    name: "Del Norte County",
    countySlug: "del-norte-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 41.749903, longitude: -123.980998 },
  },
  {
    geoid: "06017",
    stateCode: "CA",
    name: "El Dorado County",
    countySlug: "el-dorado-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 38.785612, longitude: -120.534225 },
  },
  {
    geoid: "06019",
    stateCode: "CA",
    name: "Fresno County",
    countySlug: "fresno-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 36.761006, longitude: -119.655019 },
  },
  {
    geoid: "06021",
    stateCode: "CA",
    name: "Glenn County",
    countySlug: "glenn-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 39.602546, longitude: -122.4017 },
  },
  {
    geoid: "06023",
    stateCode: "CA",
    name: "Humboldt County",
    countySlug: "humboldt-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 40.706655, longitude: -123.926176 },
  },
  {
    geoid: "06025",
    stateCode: "CA",
    name: "Imperial County",
    countySlug: "imperial-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 33.040814, longitude: -115.3554 },
  },
  {
    geoid: "06027",
    stateCode: "CA",
    name: "Inyo County",
    countySlug: "inyo-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 36.56216, longitude: -117.404209 },
  },
  {
    geoid: "06029",
    stateCode: "CA",
    name: "Kern County",
    countySlug: "kern-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 35.346629, longitude: -118.729506 },
  },
  {
    geoid: "06031",
    stateCode: "CA",
    name: "Kings County",
    countySlug: "kings-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 36.072478, longitude: -119.81553 },
  },
  {
    geoid: "06033",
    stateCode: "CA",
    name: "Lake County",
    countySlug: "lake-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 39.108009, longitude: -122.745217 },
  },
  {
    geoid: "06035",
    stateCode: "CA",
    name: "Lassen County",
    countySlug: "lassen-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 40.715287, longitude: -120.621223 },
  },
  {
    geoid: "06037",
    stateCode: "CA",
    name: "Los Angeles County",
    countySlug: "los-angeles-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 34.196398, longitude: -118.261862 },
  },
  {
    geoid: "06039",
    stateCode: "CA",
    name: "Madera County",
    countySlug: "madera-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 37.209821, longitude: -119.749802 },
  },
  {
    geoid: "06041",
    stateCode: "CA",
    name: "Marin County",
    countySlug: "marin-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 38.051367, longitude: -122.746396 },
  },
  {
    geoid: "06043",
    stateCode: "CA",
    name: "Mariposa County",
    countySlug: "mariposa-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 37.574343, longitude: -119.911721 },
  },
  {
    geoid: "06045",
    stateCode: "CA",
    name: "Mendocino County",
    countySlug: "mendocino-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 39.432388, longitude: -123.442881 },
  },
  {
    geoid: "06047",
    stateCode: "CA",
    name: "Merced County",
    countySlug: "merced-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 37.194806, longitude: -120.722802 },
  },
  {
    geoid: "06049",
    stateCode: "CA",
    name: "Modoc County",
    countySlug: "modoc-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 41.592918, longitude: -120.71837 },
  },
  {
    geoid: "06051",
    stateCode: "CA",
    name: "Mono County",
    countySlug: "mono-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 37.915836, longitude: -118.875167 },
  },
  {
    geoid: "06053",
    stateCode: "CA",
    name: "Monterey County",
    countySlug: "monterey-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 36.240104, longitude: -121.315578 },
  },
  {
    geoid: "06055",
    stateCode: "CA",
    name: "Napa County",
    countySlug: "napa-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 38.5071, longitude: -122.325904 },
  },
  {
    geoid: "06057",
    stateCode: "CA",
    name: "Nevada County",
    countySlug: "nevada-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 39.297508, longitude: -120.771343 },
  },
  {
    geoid: "06059",
    stateCode: "CA",
    name: "Orange County",
    countySlug: "orange-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 33.675687, longitude: -117.777207 },
    districts: [
      {
        geoid: "0602000",
        districtSlug: "anaheim-candidate",
        label: "Anaheim",
        playable: false,
        coverageTier: "L1_COUNTY_SHELL",
        readiness: {
          status: "candidate_only",
          sourceBasis: "census_identity",
          promotionBlocked: true,
          requiredBeforePlayable: [
            "curated_district_pack",
            "place_anchors_with_source_notes",
            "bounded_scene_compiler_proof",
            "desktop_mobile_product_loop_screenshots",
            "lumen_visual_acceptance",
            "mira_readiness_acceptance",
            "forge_split_guard",
          ],
          knownGaps: ["no_curated_places", "no_local_scene", "no_provider_normalized_categories", "not_public_quality"],
        },
      },
    ],
  },
  {
    geoid: "06061",
    stateCode: "CA",
    name: "Placer County",
    countySlug: "placer-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 39.062032, longitude: -120.722718 },
  },
  {
    geoid: "06063",
    stateCode: "CA",
    name: "Plumas County",
    countySlug: "plumas-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 39.992295, longitude: -120.824371 },
  },
  {
    geoid: "06065",
    stateCode: "CA",
    name: "Riverside County",
    countySlug: "riverside-ca",
    coverageTier: "L2_CURATED_DISTRICT",
    centroid: { latitude: 33.729828, longitude: -116.002239 },
    districts: [
      {
        geoid: "0621230",
        districtSlug: "eastvale-city-slice",
        label: "Eastvale",
        playable: true,
        coverageTier: "L2_CURATED_DISTRICT",
      },
    ],
  },
  {
    geoid: "06067",
    stateCode: "CA",
    name: "Sacramento County",
    countySlug: "sacramento-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 38.450136, longitude: -121.344329 },
  },
  {
    geoid: "06069",
    stateCode: "CA",
    name: "San Benito County",
    countySlug: "san-benito-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 36.611651, longitude: -121.085811 },
  },
  {
    geoid: "06071",
    stateCode: "CA",
    name: "San Bernardino County",
    countySlug: "san-bernardino-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 34.856661, longitude: -116.181571 },
    districts: [
      {
        geoid: "0653896",
        districtSlug: "ontario-candidate",
        label: "Ontario",
        playable: false,
        coverageTier: "L1_COUNTY_SHELL",
        readiness: {
          status: "candidate_only",
          sourceBasis: "census_identity",
          promotionBlocked: true,
          requiredBeforePlayable: [
            "curated_district_pack",
            "place_anchors_with_source_notes",
            "bounded_scene_compiler_proof",
            "desktop_mobile_product_loop_screenshots",
            "lumen_visual_acceptance",
            "mira_readiness_acceptance",
            "forge_split_guard",
          ],
          knownGaps: ["no_curated_places", "no_local_scene", "no_provider_normalized_categories", "not_public_quality"],
        },
      },
    ],
  },
  {
    geoid: "06073",
    stateCode: "CA",
    name: "San Diego County",
    countySlug: "san-diego-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 33.023604, longitude: -116.776117 },
  },
  {
    geoid: "06075",
    stateCode: "CA",
    name: "San Francisco County",
    countySlug: "san-francisco-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 37.727239, longitude: -123.032229 },
  },
  {
    geoid: "06077",
    stateCode: "CA",
    name: "San Joaquin County",
    countySlug: "san-joaquin-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 37.934982, longitude: -121.272244 },
  },
  {
    geoid: "06079",
    stateCode: "CA",
    name: "San Luis Obispo County",
    countySlug: "san-luis-obispo-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 35.388189, longitude: -120.448897 },
  },
  {
    geoid: "06081",
    stateCode: "CA",
    name: "San Mateo County",
    countySlug: "san-mateo-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 37.414672, longitude: -122.371546 },
  },
  {
    geoid: "06083",
    stateCode: "CA",
    name: "Santa Barbara County",
    countySlug: "santa-barbara-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 34.536677, longitude: -120.038364 },
  },
  {
    geoid: "06085",
    stateCode: "CA",
    name: "Santa Clara County",
    countySlug: "santa-clara-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 37.221614, longitude: -121.68954 },
  },
  {
    geoid: "06087",
    stateCode: "CA",
    name: "Santa Cruz County",
    countySlug: "santa-cruz-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 37.012347, longitude: -122.007789 },
  },
  {
    geoid: "06089",
    stateCode: "CA",
    name: "Shasta County",
    countySlug: "shasta-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 40.760514, longitude: -122.043556 },
  },
  {
    geoid: "06091",
    stateCode: "CA",
    name: "Sierra County",
    countySlug: "sierra-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 39.576925, longitude: -120.521993 },
  },
  {
    geoid: "06093",
    stateCode: "CA",
    name: "Siskiyou County",
    countySlug: "siskiyou-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 41.587986, longitude: -122.533287 },
  },
  {
    geoid: "06095",
    stateCode: "CA",
    name: "Solano County",
    countySlug: "solano-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 38.267226, longitude: -121.939594 },
  },
  {
    geoid: "06097",
    stateCode: "CA",
    name: "Sonoma County",
    countySlug: "sonoma-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 38.525182, longitude: -122.92611 },
  },
  {
    geoid: "06099",
    stateCode: "CA",
    name: "Stanislaus County",
    countySlug: "stanislaus-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 37.562316, longitude: -121.002831 },
  },
  {
    geoid: "06101",
    stateCode: "CA",
    name: "Sutter County",
    countySlug: "sutter-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 39.03619, longitude: -121.70394 },
  },
  {
    geoid: "06103",
    stateCode: "CA",
    name: "Tehama County",
    countySlug: "tehama-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 40.126157, longitude: -122.232274 },
  },
  {
    geoid: "06105",
    stateCode: "CA",
    name: "Trinity County",
    countySlug: "trinity-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 40.647858, longitude: -123.114666 },
  },
  {
    geoid: "06107",
    stateCode: "CA",
    name: "Tulare County",
    countySlug: "tulare-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 36.228834, longitude: -118.781055 },
  },
  {
    geoid: "06109",
    stateCode: "CA",
    name: "Tuolumne County",
    countySlug: "tuolumne-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 38.021434, longitude: -119.964733 },
  },
  {
    geoid: "06111",
    stateCode: "CA",
    name: "Ventura County",
    countySlug: "ventura-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 34.358748, longitude: -119.133145 },
  },
  {
    geoid: "06113",
    stateCode: "CA",
    name: "Yolo County",
    countySlug: "yolo-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 38.679609, longitude: -121.90275 },
  },
  {
    geoid: "06115",
    stateCode: "CA",
    name: "Yuba County",
    countySlug: "yuba-ca",
    coverageTier: "L1_COUNTY_SHELL",
    centroid: { latitude: 39.27013, longitude: -121.344259 },
  },
];

export function californiaCountyIndexSourceNotes(): WorldSourceNote[] {
  return [CENSUS_2024_COUNTY_GAZETTEER_SOURCE];
}
