export const HUMAN_APPROVAL_BEFORE_PERSISTENCE = "HUMAN_APPROVAL_BEFORE_PERSISTENCE" as const;
export const HUMAN_APPROVAL_BEFORE_MONEY = "HUMAN_APPROVAL_BEFORE_MONEY" as const;
export const HUMAN_APPROVAL_BEFORE_PUBLIC_CLAIM = "HUMAN_APPROVAL_BEFORE_PUBLIC_CLAIM" as const;

export const HOSTED_CLAWD_PERSISTENCE_FLAG = "ATLAS_HOSTED_CLAWD_PERSISTENCE_ENABLED" as const;
export const HOSTED_CLAWD_MONEY_FLAG = "ATLAS_HOSTED_CLAWD_MONEY_ENABLED" as const;
export const HOSTED_CLAWD_PUBLIC_CLAIM_FLAG = "ATLAS_HOSTED_CLAWD_PUBLIC_CLAIM_ENABLED" as const;
